<div class="content-header">
    <a href="shareino.com" style="width: 100%; text-align: center ; display: block">
        <img src="<?php echo $this->getSkinUrl("images/shareino_logo.png") ?>"/>
    </a>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            مدیریت ارسال محصولات به            <a href="http://shareino.ir" target="_blank">شرینو</a></h4>
    </div>
    <div class="fieldset" id="entity_form">
        <div class="hor-scroll">
            <form action="<?php echo $this->getOperationAction("syncAll"); ?>">
                <button type="submit" class="scalable save" id="ShareinoSyncAllAction" style="height: 22px">ارسال محصولات</button>
            </form>
            <form action="<?php echo $this->getOperationAction("sendCategory"); ?>">
                <button type="submit" class="scalable save" id="sendCategory" style="height: 22px">ارسال دسته بندی ها</button>
            </form>
        </div>
    </div>
</div>
