<div class="content-header">
    <a href="shareino.com" style="width: 100%; text-align: center ; display: block">
        <img src="<?php echo $this->getSkinUrl("images/shareino_logo.png") ?>"/>
    </a>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><a href="http://shareino.com">ShareINO</a> server
            synchronize operations</h4>
        <div class="form-buttons"></div>
    </div>
    <div class="fieldset " id="entity_form">
        <div class="hor-scroll">
<!--            <form action="--><?php //echo $this->getOperationAction("syncAll"); ?><!--">-->
                <button type="submit" class="scalable save" style="" id="ShareinoSyncAllAction">
                    <span><span><span>همگام سازی تمام محصولات</span></span></span></button>
<!--            </form>-->
        </div>
    </div>
</div>
